### ISSUE TITLE
Double tap is not working

### ISSUE THREAD

**Issue by amangautam1** [pedromassango/doubleClick#7]
When i double click on the view it just executes the code written for the single click.
```
view.setOnClickListener(DoubleClick(object :DoubleClickListener{
            override fun onDoubleClick(p0: View?) {
              Toast.makeText(applicationContext,"Double clicked", Toast.LENGTH_SHORT).show()
            }    
            override fun onSingleClick(p0: View?) {
               Toast.makeText(applicationContext,"Double click to open full screen", Toast.LENGTH_SHORT).show()
            }
        }))
```

**Comment by pedromassango** [comment]
Ok, I fixed it, thanks @amangautam1 .

**Comment by rasik1010** [comment]
@pedromassango i am still facing the same use , i am only getting single click event, i am not able to get double click event
